import Calendar from "./calendar.svg";
import MiniCalendar from "./mini-calendar.svg";
import EyeOff from "./eye-off.svg";
import Eye from "./eye.svg";
import Mail from "./mail.svg";
import Ticket from "./ticket.svg";
import UserPlus from "./user-plus.svg";
import User from "./user.svg";
import Layers from "./layers.svg";
import Users from "./users.svg";
import Plus from "./plus.svg";
import Edit from "./edit.svg";
import Trash from "./trash.svg";
import Coupon from "./coupon.svg";
import LogoutIcon from "./logout-icon.svg";
import ArrowLeft from "./arrow-left.svg";
import Copy from "./copy.svg";
import GearSolidFull from "./gear-solid-full.svg";
import Play from "./play.svg";
import Menu from "./menu.svg";

export { Calendar, EyeOff, Eye, Mail, Ticket, UserPlus, User, Layers, Users, Plus, Edit, Trash, MiniCalendar, Coupon, LogoutIcon, ArrowLeft, Copy, GearSolidFull, Play, Menu};
